### PR TITLE
Update peerDep range of react-native

### PR DESCRIPTION
**Pull request by kt3k**
Hello

The current peer dep range of react-native doesn't cover the latest version of react-native. This PR changes the range from `^0.32.0` to `>=0.32.0`.

http://jubianchi.github.io/semver-check/

### CODE REVIEW

**Comment by Dean177** [comment]
Thanks

**Comment by kt3k** [comment]
Could you please publish this version to npm?

**Comment by Dean177** [comment]
Yep, I will get a release out soon.

**Comment by Dean177** [comment]
@kt3k 0.1.0 is now on [npm](https://www.npmjs.com/package/react-native-json-tree)

**Comment by kt3k** [comment]
Thanks! 😄

**Pull request merged**
