### PR TITLE
Add option to copy value when touching value node

### PR DESCRIPTION
**Pull request by BenJeau**
I just found this component and I love it, but wanted to copy the value of the JSON when touching it.

__Changes__
Added new prop to the component called `copyValue`, which is passed to `JSONValueNode.js`

Please let me know if anythings needs to be changed 😃

### CODE REVIEW

**Comment by Dean177** [comment]
Hi Ben, sorry I totally missed this.

I think you can achieve this using a custom renderer https://github.com/Dean177/react-native-json-tree#customize-rendering

**Comment by Dean177** [comment]
@BenJeau ?

**Comment by BenJeau** [comment]
Oh, I think I read over that. Yeah, you're right, it works with the custom renderer

**Comment by Dean177** [comment]
That’s great. Sorry for taking so long to get back to you.

**Comment by BenJeau** [comment]
Don't worry, its good

**Pull request closed without merging**
