### PR TITLE
Feat/update npm dependencies

### PR DESCRIPTION
**Pull request by symis84**
PR related to https://github.com/Dean177/react-native-json-tree/issues/152

### CODE REVIEW

**Comment by Dean177** [comment]
@symis84 I meant vendor (copy the whole repository into this project) the fork and its dependency.

The fork was created due to this issue https://github.com/gaearon/base16-js/issues/3

If changing the version to 0.6.0 builds this fine that's great, but I suspect there will be issues since 
react-base16-styling hasn't been updated in a couple of years

**Comment by Dean177** [comment]
@symis84 ?

**Comment by felansu** [comment]
⌛

**Comment by bneigher** [comment]
@symis84 I'm unable to run this with the error:

`TypeError: styling is not a function` 

at ./src/index.js (89)

```javascript
render() {
    const {
      data: value,
      keyPath,
      postprocessValue,
      hideRoot,
      theme,
      invertTheme,
      ...rest
    } = this.props;

    const styling = createStylingFromTheme(checkLegacyTheming(theme, rest), invertTheme);

    return (
      <View {...styling('tree')}>
        <JSONNode
          hideRoot={hideRoot}
          keyPath={hideRoot ? [] : keyPath}
          postprocessValue={postprocessValue}
          styling={styling}
          value={postprocessValue(value)}
          {...rest}
        />
      </View>
    );
  }
```

styling seems to just be an empty object.  only is an issue with this fork so perhaps incompatible dep?

**Comment by Dean177** [comment]
This is superseded by #156

**Pull request closed without merging**
